[package]
name = "btagger"
edition = "2021"
version = "0.1.0"
publish = false

[dependencies]
clap = { version = "4.5.39", features = ["derive", "cargo"] }
chrono = "0.4.41"
chrono-tz = "0.10.4"
cron-parser = "0.10.0"
